# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Coin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Coin

pod 'AFNetworking', '~> 3.0'
pod 'RealmSwift'

end
